BEGIN TRANSACTION;
DELETE from category;
DELETE from questions;
DELETE from sqlite_sequence;
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("What is the capital of germany?","Berlin","Rome","Munich","Cologne");
INSERT INTO category (question_id, category_name) VALUES ("1","geography");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("Mount Everest is located in which mountain range?","Himalaya","Andes","Alps","Rocky Mountains");
INSERT INTO category (question_id, category_name) VALUES ("2","geography");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("The famous Parthenon is located in ...?","Greece","Italy","Egypt","Persia");
INSERT INTO category (question_id, category_name) VALUES ("3","geography");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("The leaning Tower of Pisa is located in ...?","Italy","Greece","Egypt","Venice");
INSERT INTO category (question_id, category_name) VALUES ("4","geography");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("The strait that connects the Mediterranean Sea and the Atlantic is the ...?","Strait of Gibraltar","Bass Strait","Cook Strait","Yucatan Strait");
INSERT INTO category (question_id, category_name) VALUES ("5","geography");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("Which of the following borders germany?","Austria","Australia","Sweden","Norway");
INSERT INTO category (question_id, category_name) VALUES ("6","geography");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("The appalachians are located in?","North America","South America","Europe","South East Asia");
INSERT INTO category (question_id, category_name) VALUES ("7","geography");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("Tasmania is located on which of these continents?","Australia","Africa","Eurasia","South America");
INSERT INTO category (question_id, category_name) VALUES ("8","geography");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("... is the capital of the US State New York","Albany","New York","New Jersey","Austin");
INSERT INTO category (question_id, category_name) VALUES ("9","geography");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("The ancient supercontinent was known as?","Pangea","Laurasia","Gondwana","Antartica");
INSERT INTO category (question_id, category_name) VALUES ("10","geography");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("The Space Needle is in which of these cities?","Seattle","Chigago","Las Vegas","Los Angeles");
INSERT INTO category (question_id, category_name) VALUES ("11","geography");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("The Empire State Building is located in ...","New York","Abu Dhabi","Las Vegas","Washington");
INSERT INTO category (question_id, category_name) VALUES ("12","geography");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("The Brandenburg Gate is located in ...","Berlin","Brandenburg","Paris","Rome");
INSERT INTO category (question_id, category_name) VALUES ("13","geography");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("Which of these is known for its famous canals?","Venice","New York","Sydney","Munich");
INSERT INTO category (question_id, category_name) VALUES ("14","geography");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("Which of these is known for its famous canals?","Amsterdam","Las Vegas","Austin","Zurich");
INSERT INTO category (question_id, category_name) VALUES ("15","geography");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("The Taj Mahal is is located in ...?","India","Egypt","Saudi Arabia","Greece");
INSERT INTO category (question_id, category_name) VALUES ("16","geography");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("Dont judge a book by its ...","Cover","Title","Author","Content");
INSERT INTO category (question_id, category_name) VALUES ("17","proverbs");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("Better safe than ...","sorry","sound","sober","sad");
INSERT INTO category (question_id, category_name) VALUES ("18","proverbs");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("Where there is smoke, there is ...","fire","someone smoking","a barbecue","smoked meat");
INSERT INTO category (question_id, category_name) VALUES ("19","proverbs");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("Actions speak louder than ...","words","pages","books","people");
INSERT INTO category (question_id, category_name) VALUES ("20","proverbs");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("The grass is always ... on the other side.","greener","taller","fresher","worse");
INSERT INTO category (question_id, category_name) VALUES ("21","proverbs");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("Still waters ...","run deep","contain fish","are toxic","evaporate");
INSERT INTO category (question_id, category_name) VALUES ("22","proverbs");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("When in Rome, ...","do as the Romans","visit the colosseum","be romantic","you are home");
INSERT INTO category (question_id, category_name) VALUES ("23","proverbs");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("Birds of a feather ... together","flock","fly","f***","feed");
INSERT INTO category (question_id, category_name) VALUES ("24","proverbs");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("The early bird chatches the ...","worm","seed","train","flu");
INSERT INTO category (question_id, category_name) VALUES ("25","proverbs");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("Learn to ... before you run.","walk","tie your shoes","run","stand");
INSERT INTO category (question_id, category_name) VALUES ("26","proverbs");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("Not all that glitters is ...","gold","glitter","silver","valuable");
INSERT INTO category (question_id, category_name) VALUES ("27","proverbs");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("Beggars can't be ...","choosers","greedy","picky","bankers");
INSERT INTO category (question_id, category_name) VALUES ("28","proverbs");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("The pen is mightier than the ...","sword","pencil","gun","fist");
INSERT INTO category (question_id, category_name) VALUES ("29","proverbs");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("Who or what waits for no one?","time","the train","the seasons","the businessman");
INSERT INTO category (question_id, category_name) VALUES ("30","proverbs");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("An apple a day keeps the doctor ...","away","healthy","at bay","fed");
INSERT INTO category (question_id, category_name) VALUES ("31","proverbs");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("The snow goose need not bathe to make itself white, neither need you do anything but ...","be yourself","bathe","pray","reflect");
INSERT INTO category (question_id, category_name) VALUES ("32","proverbs");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("A fool and his money are ...","soon parted","soon rich","headed to Vegas","best friends");
INSERT INTO category (question_id, category_name) VALUES ("33","proverbs");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("A jack of all trades is a master of ...","none","trade","business","jack");
INSERT INTO category (question_id, category_name) VALUES ("34","proverbs");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("Doctors are the worst ...","patients","mechanics","artists","friends");
INSERT INTO category (question_id, category_name) VALUES ("35","proverbs");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("Which of these is grown in water?","Rice","Watermelon","Tomato","Cucumber");
INSERT INTO category (question_id, category_name) VALUES ("36","biology");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("The mitochondria is known as the ... of the cell.","powerhouse","post office","lawyer","brain");
INSERT INTO category (question_id, category_name) VALUES ("37","biology");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("The cloudberry can be recognized by its ... colour.","orange","white","grey","purple");
INSERT INTO category (question_id, category_name) VALUES ("38","biology");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("The fastest land animal is?","Cheetah","Dachshund","Greyhound","Rabbit");
INSERT INTO category (question_id, category_name) VALUES ("39","biology");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("Tomatoes are ...","Fruits","Nuts","Vegetables","Roots");
INSERT INTO category (question_id, category_name) VALUES ("40","biology");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("Which of these is a bird?","Kiwi","Mango","Colugo","Pacay");
INSERT INTO category (question_id, category_name) VALUES ("41","biology");
INSERT INTO questions (question, answer1, answer2, answer3, answer4) VALUES ("Chlorophyll is known for its ... colour","green","beautiful","blue","white");
INSERT INTO category (question_id, category_name) VALUES ("42","biology");

COMMIT;